// <auto-generated />
using System;
using MicroservicioHotel.AccessData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MicroservicioHotel.AccessData.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20210429031841_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("5a9d055b-2ade-4942-8d2c-d8499f51fe65"),
                            Descripcion = "Habitación para una persona",
                            Nombre = "Individual"
                        },
                        new
                        {
                            CategoriaId = new Guid("f3330cae-4dda-4d2c-b649-112e96e1479d"),
                            Descripcion = "Habitación para dos personas",
                            Nombre = "Matrimonial"
                        },
                        new
                        {
                            CategoriaId = new Guid("1cb0313d-6829-4249-810a-2456f3151fad"),
                            Descripcion = "Habitación para cuatro personas",
                            Nombre = "Suite"
                        });
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.FotoHotel", b =>
                {
                    b.Property<Guid>("FotoHotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("HotelId1")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("FotoHotelId");

                    b.HasIndex("HotelId1");

                    b.ToTable("FotosHoteles");
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("HabitacionId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("HotelId");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DireccionNum")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DireccionObservaciones")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Estrellas")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Longitud")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 7)
                        .HasColumnType("decimal(10,7)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("HotelId");

                    b.ToTable("Hoteles");
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.FotoHotel", b =>
                {
                    b.HasOne("MicroservicioHotel.Domain.Entities.Hotel", "Hotel")
                        .WithMany("FotosHotel")
                        .HasForeignKey("HotelId1");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.Habitacion", b =>
                {
                    b.HasOne("MicroservicioHotel.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Habitaciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MicroservicioHotel.Domain.Entities.Hotel", "Hotel")
                        .WithMany("Habitaciones")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("MicroservicioHotel.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("FotosHotel");

                    b.Navigation("Habitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
